# Generated by Django 3.1.2 on 2020-10-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Officetels',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('rent', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contract', models.CharField(blank=True, max_length=254, null=True)),
                ('road', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('floor', models.BigIntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=254, null=True)),
                ('recent', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('station_ar', models.BigIntegerField(blank=True, null=True)),
                ('station_na', models.CharField(blank=True, max_length=254, null=True)),
                ('transfer', models.BigIntegerField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('hos_num', models.BigIntegerField(blank=True, null=True)),
                ('mart_num', models.BigIntegerField(blank=True, null=True)),
                ('fast_num', models.BigIntegerField(blank=True, null=True)),
                ('cafe_num', models.BigIntegerField(blank=True, null=True)),
                ('cul_num', models.BigIntegerField(blank=True, null=True)),
                ('con_num', models.BigIntegerField(blank=True, null=True)),
                ('laun_num', models.BigIntegerField(blank=True, null=True)),
                ('da_num', models.BigIntegerField(blank=True, null=True)),
                ('gym_num', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'officetels',
            },
        ),
        migrations.CreateModel(
            name='OneTwoRoom',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('rent', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contract', models.CharField(blank=True, max_length=254, null=True)),
                ('road', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.CharField(blank=True, max_length=254, null=True)),
                ('recent', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('station_ar', models.BigIntegerField(blank=True, null=True)),
                ('station_na', models.CharField(blank=True, max_length=254, null=True)),
                ('transfer', models.BigIntegerField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('hos_num', models.BigIntegerField(blank=True, null=True)),
                ('mart_num', models.BigIntegerField(blank=True, null=True)),
                ('fast_num', models.BigIntegerField(blank=True, null=True)),
                ('cafe_num', models.BigIntegerField(blank=True, null=True)),
                ('cul_num', models.BigIntegerField(blank=True, null=True)),
                ('con_num', models.BigIntegerField(blank=True, null=True)),
                ('laun_num', models.BigIntegerField(blank=True, null=True)),
                ('da_num', models.BigIntegerField(blank=True, null=True)),
                ('gym_num', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'one_two_room',
            },
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speed',
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('rent', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contract', models.CharField(blank=True, max_length=254, null=True)),
                ('road', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('floor', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area', models.CharField(blank=True, max_length=254, null=True)),
                ('recent', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('station_ar', models.BigIntegerField(blank=True, null=True)),
                ('station_na', models.CharField(blank=True, max_length=254, null=True)),
                ('transfer', models.BigIntegerField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('hos_num', models.BigIntegerField(blank=True, null=True)),
                ('mart_num', models.BigIntegerField(blank=True, null=True)),
                ('fast_num', models.BigIntegerField(blank=True, null=True)),
                ('cafe_num', models.BigIntegerField(blank=True, null=True)),
                ('cul_num', models.BigIntegerField(blank=True, null=True)),
                ('con_num', models.BigIntegerField(blank=True, null=True)),
                ('laun_num', models.BigIntegerField(blank=True, null=True)),
                ('da_num', models.BigIntegerField(blank=True, null=True)),
                ('gym_num', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'villa',
            },
        ),
    ]
