# Generated by Django 3.1.2 on 2020-10-20 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Officetels',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('rent', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contract', models.CharField(blank=True, max_length=254, null=True)),
                ('road', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('floor', models.BigIntegerField(blank=True, null=True)),
                ('area', models.CharField(blank=True, max_length=254, null=True)),
                ('recent', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('station_ar', models.BigIntegerField(blank=True, null=True)),
                ('station_na', models.CharField(blank=True, max_length=254, null=True)),
                ('transfer', models.BigIntegerField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('hos_num', models.BigIntegerField(blank=True, null=True)),
                ('mart_num', models.BigIntegerField(blank=True, null=True)),
                ('fast_num', models.BigIntegerField(blank=True, null=True)),
                ('cafe_num', models.BigIntegerField(blank=True, null=True)),
                ('cul_num', models.BigIntegerField(blank=True, null=True)),
                ('con_num', models.BigIntegerField(blank=True, null=True)),
                ('laun_num', models.BigIntegerField(blank=True, null=True)),
                ('da_num', models.BigIntegerField(blank=True, null=True)),
                ('gym_num', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'officetels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OneTwoRoom',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('rent', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contract', models.CharField(blank=True, max_length=254, null=True)),
                ('road', models.CharField(blank=True, max_length=254, null=True)),
                ('area', models.CharField(blank=True, max_length=254, null=True)),
                ('recent', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('station_ar', models.BigIntegerField(blank=True, null=True)),
                ('station_na', models.CharField(blank=True, max_length=254, null=True)),
                ('transfer', models.BigIntegerField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('hos_num', models.BigIntegerField(blank=True, null=True)),
                ('mart_num', models.BigIntegerField(blank=True, null=True)),
                ('fast_num', models.BigIntegerField(blank=True, null=True)),
                ('cafe_num', models.BigIntegerField(blank=True, null=True)),
                ('cul_num', models.BigIntegerField(blank=True, null=True)),
                ('con_num', models.BigIntegerField(blank=True, null=True)),
                ('laun_num', models.BigIntegerField(blank=True, null=True)),
                ('da_num', models.BigIntegerField(blank=True, null=True)),
                ('gym_num', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'one_two_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpatialRefSys',
            fields=[
                ('srid', models.IntegerField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(blank=True, max_length=256, null=True)),
                ('auth_srid', models.IntegerField(blank=True, null=True)),
                ('srtext', models.CharField(blank=True, max_length=2048, null=True)),
                ('proj4text', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'spatial_ref_sys',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(blank=True, max_length=254, null=True)),
                ('rent', models.CharField(blank=True, max_length=254, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('deposit', models.BigIntegerField(blank=True, null=True)),
                ('pay', models.BigIntegerField(blank=True, null=True)),
                ('year', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('contract', models.CharField(blank=True, max_length=254, null=True)),
                ('road', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('floor', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('area', models.CharField(blank=True, max_length=254, null=True)),
                ('recent', models.BigIntegerField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('station_ar', models.BigIntegerField(blank=True, null=True)),
                ('station_na', models.CharField(blank=True, max_length=254, null=True)),
                ('transfer', models.BigIntegerField(blank=True, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('hos_num', models.BigIntegerField(blank=True, null=True)),
                ('mart_num', models.BigIntegerField(blank=True, null=True)),
                ('fast_num', models.BigIntegerField(blank=True, null=True)),
                ('cafe_num', models.BigIntegerField(blank=True, null=True)),
                ('cul_num', models.BigIntegerField(blank=True, null=True)),
                ('con_num', models.BigIntegerField(blank=True, null=True)),
                ('laun_num', models.BigIntegerField(blank=True, null=True)),
                ('da_num', models.BigIntegerField(blank=True, null=True)),
                ('gym_num', models.BigIntegerField(blank=True, null=True)),
                ('geom', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'villa',
                'managed': False,
            },
        ),
    ]
