# Generated by Django 3.0.7 on 2020-10-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20201020_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officetels',
            options={},
        ),
        migrations.AlterModelOptions(
            name='onetworoom',
            options={},
        ),
        migrations.AlterModelOptions(
            name='speed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='villa',
            options={},
        ),
    ]
