# Generated by Django 3.1.2 on 2020-10-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'cafe',
            },
        ),
        migrations.CreateModel(
            name='Convenience',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'convenience',
            },
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'culture',
            },
        ),
        migrations.CreateModel(
            name='Daiso',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'daiso',
            },
        ),
        migrations.CreateModel(
            name='Fastfood',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'fastfood',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'health',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'laundry',
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('house_type', models.CharField(blank=True, max_length=254, null=True)),
                ('criteria', models.CharField(blank=True, max_length=254, null=True)),
                ('con_name', models.CharField(blank=True, max_length=254, null=True)),
                ('con_addres', models.CharField(blank=True, max_length=254, null=True)),
                ('con_latitu', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('con_longit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
            ],
            options={
                'db_table': 'market',
            },
        ),
    ]
