# Generated by Django 3.0.7 on 2020-10-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comfort', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafe',
            options={},
        ),
        migrations.AlterModelOptions(
            name='convenience',
            options={},
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={},
        ),
        migrations.AlterModelOptions(
            name='daiso',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fastfood',
            options={},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={},
        ),
        migrations.AlterModelOptions(
            name='laundry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='market',
            options={},
        ),
    ]
